name: Tenstorrent Blackhole Linux CI 🐧

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: tt-beta-ubuntu-2204-xlarge
    env:
      CI_JOB_ID: ${{ github.run_id }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get install -qq make
        make install_all

    - name: Clone Linux and OpenSBI
      run: make clone_all

    - name: Load ccache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache
        key: tt

    - name: Build Linux, OpenSBI and device tree
      run: |
        export PATH="/usr/lib/ccache:$PATH"
        make build_all

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tt-bh-linux
        path: |
          Image
          fw_jump.bin
          blackhole-p100.dtb

    - name: Print stats
      run: |
        ccache -s

  upload_release_artifacts:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download tt-bh-linux artifact
      uses: actions/download-artifact@v4
      with:
        name: tt-bh-linux

    - name: Upload packages to release
      run: |
        gh release upload ${{ github.ref_name }} Image fw_jump.bin blackhole-p100.dtb
      env:
        GITHUB_TOKEN: ${{ github.token }}

  generate_rootfs:
    runs-on: tt-beta-ubuntu-2204-xlarge

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -qq && sudo apt-get install -qq qemu-user-static qemu-utils debootstrap

    - name: Build disk image 
      run: |
        sudo ./build-image.sh 

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tt-bh-disk-image
        path: |
          debian-riscv64.img
